// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9z1ZBZTEidlTAV6MiklDehYP2E2lm1DQ',
    appId: '1:1059612007126:web:81e764ed50f32bd713c777',
    messagingSenderId: '1059612007126',
    projectId: 'trash2cash-4e69a',
    authDomain: 'trash2cash-4e69a.firebaseapp.com',
    storageBucket: 'trash2cash-4e69a.firebasestorage.app',
    measurementId: 'G-534ZCQ2QM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYsl8yvKVtBfJarULaIzOsuQvaN4jgOJ4',
    appId: '1:1059612007126:android:d1376bd50ab41fc013c777',
    messagingSenderId: '1059612007126',
    projectId: 'trash2cash-4e69a',
    storageBucket: 'trash2cash-4e69a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9z1ZBZTEidlTAV6MiklDehYP2E2lm1DQ',
    appId: '1:1059612007126:web:059aff5914dd09c713c777',
    messagingSenderId: '1059612007126',
    projectId: 'trash2cash-4e69a',
    authDomain: 'trash2cash-4e69a.firebaseapp.com',
    storageBucket: 'trash2cash-4e69a.firebasestorage.app',
    measurementId: 'G-QDTWRMJLM5',
  );
}
